version: '3'
services:
  microservice:
    build: .
    container_name: microservice
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - "./postgres_to_es/.env"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    env_file:
      - "./postgres_to_es/.env"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 15s
      timeout: 15s
      retries: 3
    expose:
      - "9200"
